http:
  port: ${PORT:-8080}
admin:
  port: 9876
  host: 0.0.0.0

apiEndpoints:
  pitstop-customer:
    host: '*'
    paths: '/api/customers/*'
  pitstop-vehicle:
    host: '*'
    paths: '/api/vehicles/*'
  pitstop-workshop:
    host: '*'
    paths: '/api/workshop/*'

serviceEndpoints:
  pitstop-customer-service:
    # Utilisez le FQDN complet avec le namespace
    url: 'http://pitstop-customer-service.default.svc.cluster.local:3001'
  pitstop-vehicle-service:
    url: 'http://pitstop-vehicle-service.default.svc.cluster.local:3002'
  pitstop-workshop-service:
    url: 'http://pitstop-workshop-service.default.svc.cluster.local:3003'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  customers-pipeline:
    apiEndpoints:
      - pitstop-customer
    policies:
      - cors:
          - action:
              origin: '*'
              methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
              allowedHeaders: ['Content-Type', 'Authorization']
      - proxy:
          - action:
              serviceEndpoint: pitstop-customer-service
              changeOrigin: true

  vehicles-pipeline:
    apiEndpoints:
      - pitstop-vehicle
    policies:
      - cors:
          - action:
              origin: '*'
              methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
              allowedHeaders: ['Content-Type', 'Authorization']
      - proxy:
          - action:
              serviceEndpoint: pitstop-vehicle-service
              changeOrigin: true

  workshop-pipeline:
    apiEndpoints:
      - pitstop-workshop
    policies:
      - cors:
          - action:
              origin: '*'
              methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
              allowedHeaders: ['Content-Type', 'Authorization']
      - proxy:
          - action:
              serviceEndpoint: pitstop-workshop-service
              changeOrigin: true
