http:
  port: ${PORT:-8080}
admin:
  port: 9876
  host: localhost
apiEndpoints:
  pitstop-customer:
    host: localhost
    paths: '/api/customers/*'
  pitstop-vehicle:
    host: localhost
    paths: '/api/vehicles/*'
  pitstop-workshop:
    host: localhost
    paths: '/api/workshop/*'
serviceEndpoints:
  pitstop-customer-service:
    url: ${CUSTOMER_URL:-'http://pitstop-customer-service:3001'}
  pitstop-vehicle-service:
    url: ${VEHICLE_URL:-'http://pitstop-vehicle-service:3002'}
  pitstop-workshop-service:
    url: ${WORKSHOP_URL:-'http://pitstop-workshop-service:3003'}
    
 
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  customers-pipelines:
    apiEndpoints:
      - pitstop-customer
    policies:
      - proxy:
          - action:
              serviceEndpoint: pitstop-customer-service
              changeOrigin: true
  vehicles-pipelines:
    apiEndpoints:
      - pitstop-vehicle
    policies:
      - proxy:
          - action:
              serviceEndpoint: pitstop-vehicle-service
              changeOrigin: true
  workshop-pipelines:
    apiEndpoints:
      - pitstop-workshop
    policies:
      - proxy:
          - action:
              serviceEndpoint: pitstop-workshop-service
              changeOrigin: true
