http:
  port: ${PORT:-8080}
admin:
  port: 9876
  host: 0.0.0.0  # Changé de localhost à 0.0.0.0 pour Kubernetes

apiEndpoints:
  pitstop-customer:
    host: '*'  # ✅ Accepte toutes les hosts (plus flexible pour K8s)
    paths: '/api/customers/*'
  pitstop-vehicle:
    host: '*'  # ✅ Accepte toutes les hosts
    paths: '/api/vehicles/*'
  pitstop-workshop:
    host: '*'  # ✅ Accepte toutes les hosts
    paths: '/api/workshop/*'

serviceEndpoints:
  pitstop-customer-service:
    url: ${CUSTOMER_SERVICE_URL:-'http://pitstop-customer-service:3001'}
  pitstop-vehicle-service:
    url: ${VEHICLE_SERVICE_URL:-'http://pitstop-vehicle-service:3002'}
  pitstop-workshop-service:
    url: ${WORKSHOP_SERVICE_URL:-'http://pitstop-workshop-service:3003'}

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  customers-pipeline:
    apiEndpoints:
      - pitstop-customer
    policies:
      - cors:
          - action:
              origin: '*'
              methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
              allowedHeaders: ['Content-Type', 'Authorization']
      - proxy:
          - action:
              serviceEndpoint: pitstop-customer-service
              changeOrigin: true

  vehicles-pipeline:
    apiEndpoints:
      - pitstop-vehicle
    policies:
      - cors:
          - action:
              origin: '*'
              methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
              allowedHeaders: ['Content-Type', 'Authorization']
      - proxy:
          - action:
              serviceEndpoint: pitstop-vehicle-service
              changeOrigin: true

  workshop-pipeline:
    apiEndpoints:
      - pitstop-workshop
    policies:
      - cors:
          - action:
              origin: '*'
              methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
              allowedHeaders: ['Content-Type', 'Authorization']
      - proxy:
          - action:
              serviceEndpoint: pitstop-workshop-service
              changeOrigin: true
