apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: garage
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: garage
data:
  DB_USER: dev_user
  DB_PASSWORD: dev1234567890
  DB_NAME: dev_db
  PROD_DB_USERNAME: prod_user
  PROD_DB_PASSWORD: prod1234567890
  PROD_DB_NAME: prod_db
  PROD_DB_PORT: "3306"
  MESSAGE_BUS_USERNAME: guest
  MESSAGE_BUS_PASSWORD: guest
  MESSAGE_BUS: rabbitmq-service
  MESSAGE_BUS_TIMEOUT: "5000"
------------
apiVersion: v1
kind: Namespace
metadata:
  name: garage