apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: garage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: pitstop-webapp
          image: acrtiukk.azurecr.io/pitstop-webapp:latest
          ports:
            - containerPort: 8081
          env:
            # Configuration pour communiquer avec la gateway
            - name: GATEWAY_URL
              value: "http://gateway-service:8080"
            # URLs directes vers les services (si nécessaire)
            - name: CUSTOMER_SERVICE_URL
              value: "http://pitstop-customer-service:3001"
            - name: VEHICLE_SERVICE_URL
              value: "http://pitstop-vehicle-service:3002"
            - name: WORKSHOP_SERVICE_URL
              value: "http://pitstop-workshop-service:3003"
            # Configuration pour le développement
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
