trigger:
  branches:
    include:
      - main

variables:
  IMAGE_NAME: 'pitstop-customer'
  IMAGE_TAG: $(Build.BuildId)
  ACR_NAME: acrtiukk.azurecr.io

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerInstaller@0

- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    containerRegistry: 'connect'
    repository: '$(IMAGE_NAME)'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    buildContext: '.'
    tags: |
      $(IMAGE_TAG)
